export const GETTING_ALL_CARS_LOOADING = "GETTING_ALL_CARS_LOADING";
export const GETTING_ALL_CARS_SUCCESS = "GETTING_ALL_CARS_SUCCESS";
export const GETTING_ALL_CARS_ERROR = "GETTING_ALL_CARS_ERROR";

export const SHOW_LATEST_CARS = "SHOW_LATEST_CARS";
export const SHOW_PREMIUM_CARS = "SHOW_PREMIUM_CARS";
export const SHOW_ECONOMY_CARS = "SHOW_ECONOMY_CARS";
